container:
  image: ubuntu:bionic

task:
  matrix:
    - name: Build on Ubuntu (gcc)
      install_dependencies_script:
        - apt-get update
        - apt-get install -y cmake gcc g++ libssl-dev valgrind
      script: ./ci/run_tests.sh -DBUILD_TEST_IPV6=OFF
      container:
        matrix:
          - image: ubuntu:20.04
          - image: ubuntu:16.04
          - image: ubuntu:18.04
    - name: Build on CentOS (gcc)
      install_dependencies_script:
        - yum install -y epel-release
        - yum install -y cmake3 make gcc gcc-c++ openssl-devel valgrind
      script: CMAKE=cmake3 CTEST=ctest3 ./ci/run_tests.sh -DBUILD_TEST_IPV6=OFF
      container:
        matrix:
          - image: centos:7
