container:
  image: ubuntu:bionic

task:
  matrix:
    - name: Build on Ubuntu (gcc, release)
      install_dependencies_script:
        - apt-get update
        - apt-get install -y cmake gcc g++ libssl-dev
# Workaround for
# utest_rn_sched_self_valgrind (Failed)
# utest_rn_task_valgrind (Failed)
# utest_rn_task_self_valgrind (Failed)
# utest_rn_task_wait_valgrind (Failed)
      script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Release -DBUILD_TEST_IPV6=OFF -DRUN_TEST_VALGRIND=OFF
      container:
        matrix:
          - image: ubuntu:20.04
          - image: ubuntu:16.04
          - image: ubuntu:18.04
    - name: Build on Ubuntu (gcc, debug)
      install_dependencies_script:
        - apt-get update
        - apt-get install -y cmake gcc g++ libssl-dev valgrind
      script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Debug -DBUILD_TEST_IPV6=OFF
      container:
        matrix:
          - image: ubuntu:20.04
          - image: ubuntu:16.04
          - image: ubuntu:18.04
    - name: Build on CentOS (gcc, release)
      install_dependencies_script:
        - yum install -y epel-release
        - yum install -y cmake3 make gcc gcc-c++ openssl-devel
# Workaround for
# utest_rn_sched_self_valgrind (Failed)
# utest_rn_task_valgrind (Failed)
# utest_rn_task_self_valgrind (Failed)
# utest_rn_task_wait_valgrind (Failed)
      script: CMAKE=cmake3 CTEST=ctest3 ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Release -DBUILD_TEST_IPV6=OFF -DRUN_TEST_VALGRIND=OFF
      container:
        matrix:
          - image: centos:7
    - name: Build on CentOS (gcc, debug)
      install_dependencies_script:
        - yum install -y epel-release
        - yum install -y cmake3 make gcc gcc-c++ openssl-devel valgrind valgrind-devel
      script: CMAKE=cmake3 CTEST=ctest3 ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Debug -DBUILD_TEST_IPV6=OFF
      container:
        matrix:
          - image: centos:7
